### ISSUE TITLE
On Click i wanted to hide sheet manually. is there anyway?

### ISSUE THREAD

**Issue by waleedarshad-vf** [WhatAKitty/react-native-bottom-sheet#3]

**Comment by WhatAKitty** [comment]
Hi,
    There is no method which you want.
    Or you can push a PR yourself and I will merge it as quickly.

**Comment by waleedarshad-vf** [comment]
Hi I am newbie and learning it hard way. only you can in less time :)

**Comment by WhatAKitty** [comment]
Why you want to do so ? Could you tell me your background?

**Comment by waleedarshad-vf** [comment]
on clicking item. bottom sheets gets hide, i am using react-native-share which take a second to two to appear. This spoil app experience. so i just want to hide bottom sheet only when share sheet appears.

**Comment by WhatAKitty** [comment]
react-native-share? Like react-native's ActionSheetIOS.showShareActionSheetWithOptions?

**Comment by waleedarshad-vf** [comment]
i resolved it by myself. i used mixture of react native custom sheet and react-native-share button and merge both to acquired results. it is working well with no delay.

Thanks

**Comment by WhatAKitty** [comment]
Ok.
