### ISSUE TITLE
React Native >= 0.33

### ISSUE THREAD

**Issue by desmondhume** [WhatAKitty/react-native-bottom-sheet#4]
The usage of this package with React Native >= 0.33 causes crashes whenever this or any other package invokes `onActivityResult` (due to RN 0.33 breaking change of `ActivityEventListener` interface).
@WhatAKitty there's a fork fixing this problem, are you planning to integrate / ask for a PR? 
It's a really annoying issue, and it would be great to keep the distribution of your package consistent, avoiding the spreading of forks for such a simple update.

Thanks for this package btw!

**Comment by WhatAKitty** [comment]
Ok, I'will.
