### ISSUE TITLE
Tag new version to include RN 0.47 breaking change?

### ISSUE THREAD

**Issue by davidstoker** [WhatAKitty/react-native-bottom-sheet#9]
Could you tag a new version of this package that includes the PR that was merged a while back? https://github.com/WhatAKitty/react-native-bottom-sheet/pull/8

**Comment by WhatAKitty** [comment]
OK, I will

**Comment by WhatAKitty** [comment]
https://github.com/WhatAKitty/react-native-bottom-sheet/releases/tag/1.0.3

**Comment by davidstoker** [comment]
Thank you!
